// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGBX5u9GiqRURvPGIFoExsd-Sm-n6FEt0',
    appId: '1:76046617285:web:e7b1f45f08263b8c76beac',
    messagingSenderId: '76046617285',
    projectId: 'food-ordering-5f757',
    authDomain: 'food-ordering-5f757.firebaseapp.com',
    storageBucket: 'food-ordering-5f757.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM2cA-kT_vOlVS_QURo4AoYjz8C6TV6Hs',
    appId: '1:76046617285:android:170f85876b07abf776beac',
    messagingSenderId: '76046617285',
    projectId: 'food-ordering-5f757',
    storageBucket: 'food-ordering-5f757.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkM6PgpuAip4nTkNOQHO6P0uQW7bHdnA4',
    appId: '1:76046617285:ios:4aa66fd1940b9a1b76beac',
    messagingSenderId: '76046617285',
    projectId: 'food-ordering-5f757',
    storageBucket: 'food-ordering-5f757.firebasestorage.app',
    iosBundleId: 'com.example.gdgTask1FoodOrderingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkM6PgpuAip4nTkNOQHO6P0uQW7bHdnA4',
    appId: '1:76046617285:ios:4aa66fd1940b9a1b76beac',
    messagingSenderId: '76046617285',
    projectId: 'food-ordering-5f757',
    storageBucket: 'food-ordering-5f757.firebasestorage.app',
    iosBundleId: 'com.example.gdgTask1FoodOrderingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGBX5u9GiqRURvPGIFoExsd-Sm-n6FEt0',
    appId: '1:76046617285:web:e6347f19cb90a60376beac',
    messagingSenderId: '76046617285',
    projectId: 'food-ordering-5f757',
    authDomain: 'food-ordering-5f757.firebaseapp.com',
    storageBucket: 'food-ordering-5f757.firebasestorage.app',
  );
}
